### ISSUE TITLE
non funzia

### ISSUE THREAD

**Issue by cornettolo** [squaeodiogha/PersonalMagic#7]
Exception in thread "main" java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:195)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)
Caused by: java.lang.NullPointerException
    at cardgame.DefaultCombatPhase.<init>(DefaultCombatPhase.java:10)
    at cardgame.Player.<init>(Player.java:70)
    at cardgame.CardGame.<init>(CardGame.java:42)
    at cardgame.CardGame.<clinit>(CardGame.java:35)
    ... 3 more

Process finished with exit code 1

**Comment by cornettolo** [comment]
no ok ho fixato xD
